// File generated by FlutterFire CLI.
// This is a PLACEHOLDER — run `flutterfire configure` to generate real values.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: Replace these placeholder values by running:
///   dart pub global activate flutterfire_cli
///   flutterfire configure --project=YOUR_PROJECT_ID
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── PLACEHOLDERS — Replace with real values from flutterfire configure ──

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjsWTEvnOBkC6tGbHyhPXkbDH-c_-EsHI',
    appId: '1:222271258302:web:c6c0bd54764e5784a1e8ef',
    messagingSenderId: '222271258302',
    projectId: 'digiqueue-c6605',
    authDomain: 'digiqueue-c6605.firebaseapp.com',
    storageBucket: 'digiqueue-c6605.firebasestorage.app',
    measurementId: 'G-76ZGK6K670',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCJQkJvD12SSCFLm4Lj0XLdTWy9pcjiL4',
    appId: '1:222271258302:android:dfd1742c7977254fa1e8ef',
    messagingSenderId: '222271258302',
    projectId: 'digiqueue-c6605',
    storageBucket: 'digiqueue-c6605.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.digiqueue.digitalQueue',
  );
}
